### ISSUE TITLE
Error FWPD

### ISSUE THREAD

**Issue by jusik0** [akamming/Domoticz_Thermostate_Plugin#3]
Hi,
the thermostat works only in manual mode...
 Status: User: Admin (IP: 192.168.1.112) initiated a switch command (55/Termostat - FirePlace/Weather Dependent Control/On)
2023-01-07 18:56:51.907 Status: User: Admin (IP: ::1) initiated a switch command (30/EnableCentralHeating/On)
2023-01-07 18:56:51.916 Status: User: Admin (IP: ::1) initiated a switch command (31/EnableCooling/Off)
2023-01-07 18:56:54.419 MQTT: Thermostat/SetPoint (Boiler_Setpoint)
2023-01-07 18:56:57.185 Termostat: error getting temperature from domoticz device with **idx 30,0.01,2.5**

**Comment by akamming** [comment]
Hi,

Your setup is incorrect. the plugin requires you to configure a temperature device in domoticz to be used  and this config setting has the incorrect value.  So in domoticz go to "settings" / "hardware" / this plugin and make sure the setup is incorrect.

BTW: looking at this "30,0.01,2.5" value: It looks like you have been experimenting with the new version. For this one i have not yet updated the documentation. (will do soon..)

**Comment by akamming** [comment]
UPDATE: i just found a case where this error could occur.  has now been fixed in [this commit](https://github.com/akamming/Domoticz_Thermostate_Plugin/commit/e473a57a903ed7b7196de5ac663e8991a798dc27)

**Comment by jusik0** [comment]
Thank you so much for your work, I will test 

Domoticz Version: 2022.2
Build Hash: eea9db734
Compile Date: 2022-11-05 13:05:35
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Oct 31 2022, 14:04:00) [GCC 8.3.0]
